# 实例名称
# 用来命名日志和模型参数文件
instance_name: fluency_single_model_audio_lstm_text_gate_merge

# GPU配置
use_cuda: true

# 日志配置
log_level: INFO

cache: true
temp_dir: /home/work/wav_temp_dir

# 训练数据集配置
train_dataset_path: /dataset/flu_meta_data/V1_0_6000/fluency_exp_meta_data_6000/asr_model_sample_5_train_asr_label.csv
train_audio_dir: /dataset/flu_audio_data/V1_0_consistence_5/fluency_exp_audio_data
# 评估数据集配置
eval_dataset_path: /dataset/flu_meta_data/V1_0_6000/fluency_exp_meta_data_6000/asr_model_sample_5_eval.csv
eval_audio_dir: /dataset/flu_audio_data/V1_0_consistence_5/fluency_exp_audio_data
# 预测数据集配置
predict_dataset_path:
predict_audio_path:
predict_result_save_path:

# 模型训练配置
lr: 0.001
epochs: 20
train_batch_size: 30
train_num_workers: 14
train_shuffle: true
gradient_accumulation_steps: 1

# 模型评估配置
eval_batch_size: 30
eval_num_workers: 14
eval_shuffle: true

# 模型预测配置
predict_batch_size: 3
predict_num_workers: 1

# 其他个性化配置
audio_pretrain_model: /home/work/fluency_model/tal_model_train_and_predict_env/model_core/src/models/pytorch_vggish.pth
# Bert预训练模型名称
text_pretrain_model: bert-base-uncased
# Bert模型序列最大长度
max_seq_len: 100
# Bert分类模型类别数
num_labels: 2

# DiDi多模态融合模型配置
didi_multimodel_config_file: didi_config.yaml
didi_multimodel_vocabulary_dict: /home/work/fluency_model/tal_model_train_and_predict_env/model_core/src/models/.vector_cache
didi_multimodel_audio_length: 5999
